// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANTY_p_Hk95ML2U4t_uzrrMcaEfIKT5fs',
    appId: '1:451402739791:web:20142f01659f02b9f0fa3a',
    messagingSenderId: '451402739791',
    projectId: 'test-flutter-4b625',
    authDomain: 'test-flutter-4b625.firebaseapp.com',
    storageBucket: 'test-flutter-4b625.firebasestorage.app',
    measurementId: 'G-X5FJCC6DJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBVBVMlfK7jabroCYjgstsrCUam8Mn4so',
    appId: '1:451402739791:android:e0433f28dc5effa5f0fa3a',
    messagingSenderId: '451402739791',
    projectId: 'test-flutter-4b625',
    storageBucket: 'test-flutter-4b625.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA76cLYgPJvqPAEoTc98HZrpLElKGGbRvg',
    appId: '1:451402739791:ios:73bec93c9e324598f0fa3a',
    messagingSenderId: '451402739791',
    projectId: 'test-flutter-4b625',
    storageBucket: 'test-flutter-4b625.firebasestorage.app',
    iosClientId:
        '451402739791-drpuc3a3rrb4u0h1bjmi674cq5e9p50u.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA76cLYgPJvqPAEoTc98HZrpLElKGGbRvg',
    appId: '1:451402739791:ios:73bec93c9e324598f0fa3a',
    messagingSenderId: '451402739791',
    projectId: 'test-flutter-4b625',
    storageBucket: 'test-flutter-4b625.firebasestorage.app',
    iosClientId:
        '451402739791-drpuc3a3rrb4u0h1bjmi674cq5e9p50u.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANTY_p_Hk95ML2U4t_uzrrMcaEfIKT5fs',
    appId: '1:451402739791:web:9b5bf5dd8c0e9facf0fa3a',
    messagingSenderId: '451402739791',
    projectId: 'test-flutter-4b625',
    authDomain: 'test-flutter-4b625.firebaseapp.com',
    storageBucket: 'test-flutter-4b625.firebasestorage.app',
    measurementId: 'G-XVGRFWWV5P',
  );
}
